[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
program-b = "AuL9Qx4GSSDHmBQcpa3EWxtYEVC9HhtChTL1V5SknV76"
program_a = "87e1rrxPrWHYih5KhxkdaN5Mb3SHZk6w1JbVP9sgyhv5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
